In [13]:
import pandas as pd
import os
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

In [14]:
file_path = '../datasets/PartnerContacts.xlsx' 
PartnerContacts = pd.read_excel(file_path)

In [15]:
#Посмотрим на количество данных в Excel файле
print("Размер таблицы (строки, столбцы):", PartnerContacts.shape)

Размер таблицы (строки, столбцы): (581, 9)

In [16]:
print("Названия колонок:", PartnerContacts.columns.tolist())

Названия колонок: ['Ref', 'DeletionMark', 'Code', 'Description', 'Должность', 'Комментарий', 'КонтактноеЛицо', 'РольКонтактногоЛица', 'TTID']

In [17]:
#Посмотрим на значения данных в PartnerContacts
PartnerContacts.head(20)

,Ref,DeletionMark,Code,Description,Должность,Комментарий,КонтактноеЛицо,РольКонтактногоЛица,TTID
0,b7aade5c-9582-11e8-80cf-00155ddeca01,False,12402,Онянова Люсьена,NaN,NaN,b7aade5a-9582-11e8-80cf-00155ddeca01,00000000-0000-0000-0000-000000000000,0
1,f8cdaa0b-9b20-11e8-80d0-00155ddeca01,False,12445,Дарья Кошкина,NaN,NaN,2d71b9fb-eada-11e7-80cc-00155ddeca01,00000000-0000-0000-0000-000000000000,0
2,5e1d21d5-8177-11e5-a59e-002590f18851,False,7499,Адамчук Андрей,NaN,NaN,5e1d21d3-8177-11e5-a59e-002590f18851,00000000-0000-0000-0000-000000000000,0
3,505854c2-f160-11e8-80d1-00155ddeca01,False,13183,Екатерина,NaN,NaN,7587c2f5-e733-11e3-9011-0025906734d9,00000000-0000-0000-0000-000000000000,0
4,a1d40425-fbca-11e5-b507-002590f18851,False,8121,Булатников Кирилл,NaN,NaN,a1d40423-fbca-11e5-b507-002590f18851,00000000-0000-0000-0000-000000000000,0
5,689ee7a6-08bd-11e8-80cc-00155ddeca01,False,11271,Чепарин Андрей,NaN,NaN,689ee7a4-08bd-11e8-80cc-00155ddeca01,00000000-0000-0000-0000-000000000000,0
6,043c14a6-f602-11e7-80cc-00155ddeca01,False,11141,Ялчигулова Регина Салаватовна,NaN,NaN,b3ea66b4-192e-11e7-80c8-00155ddeca01,00000000-0000-0000-0000-000000000000,0
7,746c1617-18a9-11e9-80d3-00155ddeca01,False,13777,Лебедева Ирина Юрьевна,NaN,NaN,746c1615-18a9-11e9-80d3-00155ddeca01,00000000-0000-0000-0000-000000000000,0
8,d1539cce-8973-11e7-80cb-00155ddeca01,False,10289,Виктория,NaN,NaN,d1539ccc-8973-11e7-80cb-00155ddeca01,00000000-0000-0000-0000-000000000000,0
9,65edc626-01da-11e9-80d2-00155ddeca01,False,13431,ДИСПЕТЧЕР МИКРОАВТОБУСЫ И ЛЕГК,NaN,NaN,65edc624-01da-11e9-80d2-00155ddeca01,00000000-0000-0000-0000-000000000000,0
10,5782f664-01da-11e9-80d2-00155ddeca01,False,13430,ДИСПЕТЧЕР АВТОБУСЫ,NaN,NaN,5782f662-01da-11e9-80d2-00155ddeca01,00000000-0000-0000-0000-000000000000,0
11,7b77ed3c-3ecc-11e6-b507-002590f18851,False,8379,Сергей,NaN,NaN,0ca3361a-0210-11e6-b507-002590f18851,00000000-0000-0000-0000-000000000000,0
12,d467bbc9-4dab-11e6-b507-002590f18851,False,8436,Белоусова Елена,NaN,NaN,d467bbc7-4dab-11e6-b507-002590f18851,00000000-0000-0000-0000-000000000000,0
13,a2c585ca-de90-11e4-9830-002590f18851,False,6615,Елена Лысикова,NaN,NaN,edd2afd5-fdc1-11e3-b4a7-002590f18851,00000000-0000-0000-0000-000000000000,0
14,5a540422-afab-11ea-80d7-00155d6f0a01,False,20750,контролер управления Наро-Фоминск Ермолаева Анна,Закупщик,NaN,6cc53f2b-3b98-11eb-80d8-00155d6f0a01,00000000-0000-0000-0000-000000000000,0
15,74bed025-8eaf-11e9-80d5-00155d6f0a01,False,15102,Василина,NaN,NaN,708b9fd5-1c82-11e4-b4a7-002590f18851,00000000-0000-0000-0000-000000000000,0
16,4d65701d-f78a-11e8-80d1-00155ddeca01,False,13274,Ольга Емельянова,NaN,NaN,12e8aad5-1d59-11e8-80cc-00155ddeca01,00000000-0000-0000-0000-000000000000,0
17,594f8094-c9e3-11e3-98d9-0025906734d9,False,267,Емельянова Ольга,NaN,NaN,594f8093-c9e3-11e3-98d9-0025906734d9,00000000-0000-0000-0000-000000000000,4326
18,f5f5c276-3a58-11e7-80c9-00155ddeca01,False,9804,Губанова Вероника,NaN,NaN,0f3be3c9-1306-11e7-80c7-00155ddeca01,00000000-0000-0000-0000-000000000000,0
19,56f69b95-4692-11e6-b507-002590f18851,False,8407,Мельник Владлен,NaN,NaN,56f69b93-4692-11e6-b507-002590f18851,00000000-0000-0000-0000-000000000000,0

In [18]:
#Оставим в PartnerContacts нужные колонки для работы
columns_to_keep = [
    'Ref', 'DeletionMark', 'Code', 'Description', 'Должность', 'Комментарий', 'КонтактноеЛицо'
]

In [19]:
# Проверка наличия колонок
missing_columns = [col for col in columns_to_keep if col not in PartnerContacts.columns]

if missing_columns:
    print("В датафрейме отсутствуют следующие колонки:")
    for col in missing_columns:
        print(" -", col)

# Фильтрация по доступным колонкам
available_columns = [col for col in columns_to_keep if col in PartnerContacts.columns]
PartnerContacts_filtered = PartnerContacts[available_columns]

# Проверка, что в PartnerContacts_filtered остались только нужные колонки
if set(PartnerContacts_filtered.columns) == set(columns_to_keep):
    print("В датафрейме остались только нужные колонки.")
else:
    extra_columns = set(PartnerContacts_filtered.columns) - set(columns_to_keep)
    if extra_columns:
        print("Остались лишние колонки в отфильтрованном датафрейме:")
        for col in extra_columns:
            print(" -", col)

# Вывод результата
print("\nРазмер отфильтрованного датафрейма:", PartnerContacts_filtered.shape)
PartnerContacts_filtered.head()

В датафрейме остались только нужные колонки.

Размер отфильтрованного датафрейма: (581, 7)

,Ref,DeletionMark,Code,Description,Должность,Комментарий,КонтактноеЛицо
0,b7aade5c-9582-11e8-80cf-00155ddeca01,False,12402,Онянова Люсьена,NaN,NaN,b7aade5a-9582-11e8-80cf-00155ddeca01
1,f8cdaa0b-9b20-11e8-80d0-00155ddeca01,False,12445,Дарья Кошкина,NaN,NaN,2d71b9fb-eada-11e7-80cc-00155ddeca01
2,5e1d21d5-8177-11e5-a59e-002590f18851,False,7499,Адамчук Андрей,NaN,NaN,5e1d21d3-8177-11e5-a59e-002590f18851
3,505854c2-f160-11e8-80d1-00155ddeca01,False,13183,Екатерина,NaN,NaN,7587c2f5-e733-11e3-9011-0025906734d9
4,a1d40425-fbca-11e5-b507-002590f18851,False,8121,Булатников Кирилл,NaN,NaN,a1d40423-fbca-11e5-b507-002590f18851

In [20]:
# Замена всех NaN
PartnerContacts_filtered = PartnerContacts_filtered.fillna("Not Information")
PartnerContacts_filtered.head()

,Ref,DeletionMark,Code,Description,Должность,Комментарий,КонтактноеЛицо
0,b7aade5c-9582-11e8-80cf-00155ddeca01,False,12402,Онянова Люсьена,Not Information,Not Information,b7aade5a-9582-11e8-80cf-00155ddeca01
1,f8cdaa0b-9b20-11e8-80d0-00155ddeca01,False,12445,Дарья Кошкина,Not Information,Not Information,2d71b9fb-eada-11e7-80cc-00155ddeca01
2,5e1d21d5-8177-11e5-a59e-002590f18851,False,7499,Адамчук Андрей,Not Information,Not Information,5e1d21d3-8177-11e5-a59e-002590f18851
3,505854c2-f160-11e8-80d1-00155ddeca01,False,13183,Екатерина,Not Information,Not Information,7587c2f5-e733-11e3-9011-0025906734d9
4,a1d40425-fbca-11e5-b507-002590f18851,False,8121,Булатников Кирилл,Not Information,Not Information,a1d40423-fbca-11e5-b507-002590f18851

In [21]:
#Посмотрим на уникальные значения каждой колонки
for col in PartnerContacts_filtered.columns:
    print(f"\nУникальные значения в колонке '{col}': ({PartnerContacts_filtered[col].nunique()} всего)")
    print(PartnerContacts_filtered[col].value_counts().head(10))

Уникальные значения в колонке 'Ref': (581 всего)
b7aade5c-9582-11e8-80cf-00155ddeca01    1
74ab8a2d-4648-11e9-80d3-00155ddeca01    1
fa862aa2-471c-11e9-80d3-00155ddeca01    1
0845f3f6-be5d-11e8-80d0-00155ddeca01    1
dd182422-3b2d-11e9-80d3-00155ddeca01    1
dba5ca89-4729-11e9-80d3-00155ddeca01    1
6e3e3e2f-e7ec-11e8-80d0-00155ddeca01    1
bba07684-8071-11e4-b40d-002590f18851    1
91ab56c0-5178-11ea-80d7-00155d6f0a01    1
7b915bbd-93e7-11e8-80cf-00155ddeca01    1
Name: Ref, dtype: int64

Уникальные значения в колонке 'DeletionMark': (2 всего)
False    570
True      11
Name: DeletionMark, dtype: int64

Уникальные значения в колонке 'Code': (581 всего)
12402    1
14414    1
14440    1
12770    1
14295    1
14443    1
13097    1
6169     1
17329    1
12381    1
Name: Code, dtype: int64

Уникальные значения в колонке 'Description': (518 всего)
АГНИЯ                         9
Екатерина                     5
Елена                         5
Зубаровский Сергей Юрьевич    4
 Елена                        3
Ольга                         3
Светлана                      2
Марцев Павел Александрович    2
 Анна                         2
Вербова Елена Владимировна    2
Name: Description, dtype: int64

Уникальные значения в колонке 'Должность': (5 всего)
Not Information                             577
Закупщик                                      1
Ведущий инженер Административного отдела      1
1                                             1
Ассистент руководства                         1
Name: Должность, dtype: int64

Уникальные значения в колонке 'Комментарий': (1 всего)
Not Information    581
Name: Комментарий, dtype: int64

Уникальные значения в колонке 'КонтактноеЛицо': (537 всего)
a76349b4-650c-11e9-80d3-00155ddeca01    9
b47e50c7-f84b-11e6-80c4-00155ddeca07    3
3764f4b2-7425-11e5-a59e-002590f18851    3
4af1d8b2-c9e6-11e3-98d9-0025906734d9    3
fecdab2f-4961-11e8-80cf-00155ddeca01    2
7618f91b-1dfa-11e4-b4a7-002590f18851    2
4760c280-b735-11e4-b40d-002590f18851    2
76eda8c3-5062-11e4-b4a7-002590f18851    2
b29d605f-a76a-11e8-80d0-00155ddeca01    2
2b37ea60-9fd8-11e4-b40d-002590f18851    2
Name: КонтактноеЛицо, dtype: int64

In [22]:
# Убедимся, что папка существует
output_dir = '../filtered_datasets'
os.makedirs(output_dir, exist_ok=True)

# Путь к файлу
output_path = os.path.join(output_dir, 'PartnerContacts_filtered.xlsx')

# Сохраняем в Excel
PartnerContacts_filtered.to_excel(output_path, index=False)

# Открываем файл и настраиваем ширину колонок, из-за влияния на отображение данных
wb = load_workbook(output_path)
ws = wb.active

for i, column_cells in enumerate(ws.columns, 1):
    max_length = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells)
    adjusted_width = max_length + 2
    ws.column_dimensions[get_column_letter(i)].width = adjusted_width

# Сохраняем изменения
wb.save(output_path)
print(f"Файл сохранен: {output_path}")

Файл сохранен: ../filtered_datasets\PartnerContacts_filtered.xlsx